languages = {
    "ru": {
        "buttons": {
            "download": "Загрузить",
            "open": "Открыть",
            "settings": "Настройки",
            "clear-graph": "Очистить график",
            "add-site": "Добавить",
            "build": "Построить",
            "show": "Показать",
        },
        "data-tab": {
            "label": "Данные",
            "graph-site-data": {
                "title": "Данные",
                "xaxis": "Время",
            },
            "selection-sats": "Спутник",
            "selection-sites": "Станция",
            "input-period-time": "Сек.",
            "input-hmax": "Макс. высота:",
            "input-half-thickness": "Толщина:",
            "input-z": "Z шаг",
            "input-z-start": "Z начало",
            "input-z-end": "Z конец",
        },
        "tab-adding-site":{
            "label": "Добавление виртуальной станции",
            "lat": "Широта",
            "lon": "Долгота",
            "name": "Имя",
        },
        "download_window": {
            "title": "Скачать навигационный файл",
            "label": "Дата",
            "successаfuly": "Файл загружается",
            "unsuccessаfuly": "Дата введена неверно",
            "repeat-action": "Этот файл уже загружен",
            "error": "Произошла ошибка при скачивании",
            "unknown": "Неизвестно",
        },
        "open_window": {
            "title": "Открыть навигационный файл",
            "label": "Файл",
        },
        "time_selection": {
            "date": "Дата",
            "time": "Время",
            "not-ready": "Вертикальный TEC ещё вычисляется",
            "server-problems": "Проблемы с сервером",
        }
    },
    "en": {
        "buttons": {
            "download": "Download",
            "open": "Open",
            "settings": "Settings",
            "clear-graph": "Clear chart",
            "add-site": "Add",
            "build": "Build",
            "show": "Show",
        },
        "data-tab": {
            "label": "Data products series",
            "graph-site-data": {
                "title": "Data products series",
                "xaxis": "Time",
            },
            "selection-sats": "Satellite",
            "selection-sites": "Sites",
            "input-period-time": "Sec.",
            "input-hmax": "Max h:",
            "input-half-thickness": "Thickness:",
            "input-z": "Z step",
            "input-z-start": "Z start",
            "input-z-end": "Z end",
            "cell-size": "Cell size:",
        },
        "tab-adding-site":{
            "label": "Adding a virtual site",
            "lat": "Latitude",
            "lon": "Longitude",
            "name": "Name",
        },
        "download_window": {
            "title": "Download navigation file",
            "label": "Date",
            "successаfuly": "File is loading",
            "unsuccessаfuly": "The date is entered incorrectly",
            "repeat-action": "This file has already been downloaded",
            "error": "There was an error while downloading",
            "unknown": "Unknown",
        },
        "open_window": {
            "title": "Open navigation file",
            "label": "File",
        },
        "time_selection": {
            "date": "Date",
            "time": "Time",
            "not-ready": "Vertical TEC is still being calculated",
            "server-problems": "Server problems",
        }
    },
}